# Generated by Django 2.2.1 on 2019-06-26 23:40

import Application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=Application.models.image_folder),
        ),
    ]
