# Generated by Django 2.2.1 on 2019-06-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_auto_20190627_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
