# Generated by Django 2.2.1 on 2019-06-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_remove_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
