# Generated by Django 2.2.1 on 2019-06-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_auto_20190627_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avaible',
            field=models.BooleanField(default=True),
        ),
    ]
